# Generated by Django 5.2.4 on 2025-07-08 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_brand_smokelog_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='smokelog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smokelog',
            name='mood_after',
            field=models.IntegerField(choices=[(1, '😫 Very Bad'), (2, '😞 Bad'), (3, '😐 Neutral'), (4, '😊 Good'), (5, '😄 Very Good')], default=3),
        ),
        migrations.AddField(
            model_name='smokelog',
            name='mood_before',
            field=models.IntegerField(choices=[(1, '😫 Very Bad'), (2, '😞 Bad'), (3, '😐 Neutral'), (4, '😊 Good'), (5, '😄 Very Good')], default=3),
        ),
        migrations.AddField(
            model_name='smokelog',
            name='trigger',
            field=models.CharField(choices=[('stress', 'Stress'), ('boredom', 'Boredom'), ('social', 'Social'), ('habit', 'Habit/Routine'), ('craving', 'Craving'), ('after_meal', 'After Meal'), ('break', 'Work Break'), ('alcohol', 'With Alcohol'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='smokelog',
            name='note',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
