# Generated by Django 5.2.4 on 2025-07-08 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_brand_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('stress', 'Stress'), ('boredom', 'Boredom'), ('social', 'Social'), ('habit', 'Habit/Routine'), ('craving', 'Craving'), ('after_meal', 'After Meal'), ('break', 'Work Break'), ('alcohol', 'With Alcohol'), ('other', 'Other')], default='other', max_length=20)),
                ('mood_before', models.IntegerField(choices=[(1, '😫 Very Bad'), (2, '😞 Bad'), (3, '😐 Neutral'), (4, '😊 Good'), (5, '😄 Very Good')], default=3)),
                ('mood_after', models.IntegerField(choices=[(1, '😫 Very Bad'), (2, '😞 Bad'), (3, '😐 Neutral'), (4, '😊 Good'), (5, '😄 Very Good')], default=3)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.brand')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
