# Generated by Django 5.2.4 on 2025-07-08 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_userdefault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='price',
        ),
        migrations.RemoveField(
            model_name='smokelog',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='userdefault',
            name='brand',
        ),
        migrations.CreateModel(
            name='UserBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['brand__name'],
                'unique_together': {('user', 'brand')},
            },
        ),
        migrations.AddField(
            model_name='smokelog',
            name='user_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.userbrand'),
        ),
        migrations.AddField(
            model_name='userdefault',
            name='user_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.userbrand'),
        ),
    ]
