# Generated by Django 5.2.4 on 2025-07-08 17:32

from django.db import migrations

def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('tracker', 'Profile')
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_profile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
