# Generated by Django 5.2.4 on 2025-07-08 17:35

from django.db import migrations

def update_timezone(apps, schema_editor):
    Profile = apps.get_model('tracker', 'Profile')
    Profile.objects.filter(timezone='Asia/Dacca').update(timezone='Asia/Dhaka')

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20250708_2332'),
    ]

    operations = [
        migrations.RunPython(update_timezone),
    ]
