# Generated by Django 5.2.4 on 2025-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20250708_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
