# Generated by Django 5.0.6 on 2025-07-14 04:32

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('tracker', 'Profile')
    for user in User.objects.filter(profile__isnull=True):
        Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_brandrequest'),
    ]

    operations = [
        migrations.RunPython(create_profiles),
    ]
