# Generated by Django 5.2.4 on 2025-07-15 17:21

from django.db import migrations

def create_initial_achievements(apps, schema_editor):
    Achievement = apps.get_model('tracker', 'Achievement')
    achievements_data = [
        {'title': 'First Log', 'description': 'Log your first smoke', 'points_reward': 10},
        {'title': 'First Smoke-Free Day', 'description': 'Complete 1 smoke-free day', 'points_reward': 50},
        {'title': '7-Day Streak', 'description': '7 smoke-free days in a row', 'points_reward': 300},
        {'title': '30-Day Streak', 'description': '30 smoke-free days in a row', 'points_reward': 1000},
    ]
    for data in achievements_data:
        Achievement.objects.get_or_create(title=data['title'], defaults=data)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_achievement_userpoints_userachievement'),
    ]

    operations = [
        migrations.RunPython(create_initial_achievements),
    ]
