# Generated by Django 5.2.4 on 2025-07-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_seed_achievements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('logging', 'Logging'), ('streak', 'Streak'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='achievement',
            name='criteria_type',
            field=models.CharField(blank=True, choices=[('total_logs', 'Total Logs'), ('streak_days', 'Streak Days')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='criteria_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoints',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userpoints', to=settings.AUTH_USER_MODEL),
        ),
    ]
