# Generated by Django 5.2.4 on 2025-07-16 09:49

from django.db import migrations

def populate_achievement_criteria(apps, schema_editor):
    Achievement = apps.get_model('tracker', 'Achievement')
    achievements_data = [
        {
            'title': 'First Log', 'description': 'Log your first smoke', 'points_reward': 10,
            'achievement_type': 'logging', 'criteria_type': 'total_logs', 'criteria_value': 1
        },
        {
            'title': 'First Smoke-Free Day', 'description': 'Complete 1 smoke-free day', 'points_reward': 50,
            'achievement_type': 'streak', 'criteria_type': 'streak_days', 'criteria_value': 1
        },
        {
            'title': '7-Day Streak', 'description': '7 smoke-free days in a row', 'points_reward': 300,
            'achievement_type': 'streak', 'criteria_type': 'streak_days', 'criteria_value': 7
        },
        {
            'title': '30-Day Streak', 'description': '30 smoke-free days in a row', 'points_reward': 1000,
            'achievement_type': 'streak', 'criteria_type': 'streak_days', 'criteria_value': 30
        },
    ]
    for data in achievements_data:
        Achievement.objects.update_or_create(title=data['title'], defaults=data)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_achievement_achievement_type_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_achievement_criteria),
    ]
